### ISSUE TITLE
IP v2 to-do list

### ISSUE THREAD

**Issue by lokka30** [lokka30/InfiPlace#3]
- [ ] rename to InfinityItems
- [ ] re-code
- [ ] Multiline messages.
- [ ] Unlimited snowballs/eggs - suggested by `T_nology`
- [ ] Permissions for each individual material
